# Site settings
title: Erin
email: festethejester@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Erin's site is under construction
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erindb.com" # the base hostname & protocol for your site
github_username:  feste

# Build settings
markdown: kramdown
